 export const STATIC_VARIABLE = {
  orderStatusArray:  [
    { value: 1, label: 'Pending Payment', color: 'rgb(255, 166, 0)' },
    { value: 2, label: 'Processing', color: 'purple' },
    { value: 3, label: 'Cancel', color: 'gary' },
    { value: 4, label: 'Completed', color: '#66bb6a' },
    { value: 5, label: 'Failed', color: '#f44336'  },
   ],
   voucherDiscountTypeArray:  [
    { value: 1, label: 'RM' },
    { value: 2, label: '%' },
   ],
   malaysiaBankArray: [
   { label: 'Affin Bank', value: 1},
   { label: 'Agrobank', value: 2},
   { label: 'Alliance Bank(Personal)', value: 3},
   { label: 'Ambank', value: 4},
   { label: 'Bank Islam', value: 5},
   { label: 'Bank Muamalat', value: 6},
   { label: 'Bank Rakyat', value: 7},
   { label: 'BSN', value: 8},
   { label: 'CIMB Clicks', value: 9},
   { label: 'Hong Leong Bank', value: 10},
   { label: 'HSBC Bank', value: 11},
   { label: 'KFH', value: 12},
   { label: 'Maybank2U', value: 13},
   { label: 'OCBC Bank', value: 14},
   { label: 'Public Bank', value: 15},
   { label: 'RHB Bank', value: 16},
   { label: 'Standard Chartered', value: 17},
   { label: 'UOB Bank', value: 18},
   ],
   claimStatusArray:  [
    { value: 1, label: 'Pending' },
    { value: 2, label: 'Claimed' },
    { value: 3, label: 'Cancel' },
    { value: 4, label: 'Suspend' },
   ],
  levelStatusArray: [
      {value: 1, label: 'Basic', color: '#A0784D' },
      {value: 2, label: 'VIP', color: '#A3B5C1'},
      {value: 3, label: 'VVIP', color: '#CEAC07'},
  ],
 }